# Site settings
# title: Great New Blog Title
# author:
#   name: Evan Will
#   email: your-email@domain.com
# description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
